srilm_path = '/Users/spencerlake/Dropbox/upenn/senior_design/srilm-1.7.1/bin/macosx'
temp_train_file = 'temp_train.txt'
language_model_file = 'ngram_model.lm'
temp_test_file = 'temp_test.txt'
output_test_file = 'output.txt'
